'use client'
import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Calculator, CheckCircle2, Landmark, LockKeyhole, Menu, PiggyBank, ShieldCheck, TrendingUp, Users, X, MessageCircle } from 'lucide-react'

const products = [
  { icon: PiggyBank, title: 'Savings Account', copy: 'Build a strong financial cushion with flexible everyday saving.', rate: 'From 5.5%', label: 'annual dividend' },
  { icon: TrendingUp, title: 'Fixed Deposit', copy: 'Put your money to work with predictable, competitive returns.', rate: 'Up to 10%', label: 'annual return' },
  { icon: Users, title: 'Junior Savings', copy: 'A bright start for the next generation of Kenyan savers.', rate: 'From 6%', label: 'annual dividend' },
  { icon: ShieldCheck, title: 'Emergency Loan', copy: 'Quick support when life brings an unexpected expense.', rate: '10%', label: 'reducing balance' },
  { icon: Landmark, title: 'Development Loan', copy: 'Grow your home, farm, education or personal projects.', rate: '12%', label: 'reducing balance' },
  { icon: TrendingUp, title: 'Business Loan', copy: 'Capital that helps your enterprise move from plan to progress.', rate: '14%', label: 'reducing balance' },
]
const testimonials = [
  ['Mary', 'Member for 6 years', '“Ezra helped me turn small, consistent savings into a new chapter for my family.”'],
  ['Brian', 'Member for 4 years', '“The business loan process was clear, human and built around my goals.”'],
  ['Amina', 'Member for 8 years', '“I always know where my money is going, and I feel part of something bigger.”'],
]
function money(value:number){ return `KES ${Math.round(value).toLocaleString('en-KE')}` }
export default function Home(){
  const [menu,setMenu]=useState(false); const [amount,setAmount]=useState(250000); const [term,setTerm]=useState(24); const [cookies,setCookies]=useState(false); const [preferences,setPreferences]=useState(false)
  useEffect(()=>{setCookies(localStorage.getItem('ezra-cookie-consent')!=='accepted')},[])
  const acceptCookies=()=>{localStorage.setItem('ezra-cookie-consent','accepted');setCookies(false)}
  const monthly=useMemo(()=>{const r=.12/12;return amount*r*Math.pow(1+r,term)/(Math.pow(1+r,term)-1)},[amount,term])
  return <>
    {cookies&&<div className="cookie-banner"><div><strong>Ezra SACCO uses cookies</strong><span> to personalise your member experience and improve security. <a href="/legal/cookie-policy">See our Cookie Policy.</a></span></div><div className="cookie-actions"><button className="button button-primary" onClick={acceptCookies}>Accept All</button><button className="button button-outline" onClick={()=>setPreferences(!preferences)}>Manage Preferences</button></div>{preferences&&<div className="cookie-preferences"><label>Necessary <input type="checkbox" checked readOnly/></label><label>Analytics <input type="checkbox"/></label><label>Functional <input type="checkbox"/></label><button className="button button-primary" onClick={acceptCookies}>Save preferences</button></div>}</div>}
    <div className="topline"><div className="container"><span><strong>Licensed by SASRA</strong> · Member funds insured</span><div className="toplinks"><span>+254 112 272 061</span><span>Nairobi, Kenya</span></div></div></div>
    <header className="navbar"><div className="container nav-inner"><a className="logo" href="#home"><span className="crest">E</span><span>Ezra<br/><small>SACCO</small></span></a><nav className="navlinks"><a href="#home">Home</a><a href="#about">About</a><a href="#products">Products</a><a href="#calculator">Loans</a><a href="#invest">Invest</a><a href="#news">News</a><a href="#contact">Contact</a></nav><div className="nav-actions"><a className="login" href="/portal">Member Login</a><a className="button button-primary" href="/join">Join Now <ArrowRight size={15}/></a></div><button className="menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    {menu&&<div className="mobile-drawer"><div className="container"><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#products" onClick={()=>setMenu(false)}>Products</a><a href="#calculator" onClick={()=>setMenu(false)}>Loans</a><a href="#invest" onClick={()=>setMenu(false)}>Invest</a><a href="#news" onClick={()=>setMenu(false)}>News</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a><a href="/join">Join Now</a></div></div>}
    <div className="badgebar"><div className="container"><span><i className="dot"/> SASRA Licensed</span><span><i className="dot"/> Member funds insured</span><span><i className="dot"/> Serving Kenya since 2004</span></div></div>
    <main>
      <section className="hero" id="home"><div className="container hero-grid"><div><div className="eyebrow">A better way to move forward</div><h1><span>Save</span><span>Together.</span><span>Grow</span><span>Together.</span><span>Prosper</span><span>Together.</span></h1><p>Ezra SACCO is your trusted financial partner. Build with a community that believes your goals are worth investing in.</p><div className="actions"><a className="button button-primary" href="/join">Become a Member <ArrowRight size={15}/></a><a className="button button-outline" href="/apply/loan">Apply for a Loan</a></div><div className="trust"><div><strong>KES 2.4B</strong><small>member deposits</small></div><div><strong>48,000</strong><small>members growing</small></div><div><strong>20 yrs</strong><small>of trusted service</small></div></div></div><div className="hero-art"><div className="art-card"><div className="art-copy"><b>Your progress<br/>starts here.</b><span>Shared purpose. Shared prosperity.</span></div></div><div className="floating-stat"><strong>10.5%</strong>average member dividend</div></div></div></section>
      <section className="story section" id="about"><div className="container story-grid"><div className="story-image"><img src="/images/community.jpg" alt="Ezra member building her business"/><div className="image-note"><strong>20</strong><span>years of<br/>shared progress</span></div></div><div className="story-copy"><div className="eyebrow">More than a financial institution</div><h2>A little more room to grow.</h2><p>Good money decisions should feel clear, considered and personal. Ezra gives you the confidence to save intentionally, borrow responsibly and build a future that feels like your own.</p><div className="story-points"><div><span>01</span><strong>Member-first</strong><small>Your goals set the pace.</small></div><div><span>02</span><strong>Built on trust</strong><small>Clear terms, real support.</small></div></div><a className="text-link" href="/about">Discover Ezra <ArrowRight size={14}/></a></div></div></section>
      <section className="section" id="products"><div className="container"><div className="section-head"><div><div className="eyebrow">Products built around you</div><h2>Put your money to work</h2></div><p>Simple, secure products for salaried workers, entrepreneurs, farmers, groups and Kenyans abroad.</p></div><div className="cards">{products.map(({icon:Icon,title,copy,rate,label})=><article className="card" key={title}><div className="icon"><Icon size={23}/></div><h3>{title}</h3><p>{copy}</p><div className="rate">{rate} <small>{label}</small></div><div className="card-foot"><a className="text-link" href="/products/savings-account">Learn more</a><a className="text-link" href="/join">Apply <ArrowRight size={14}/></a></div></article>)}</div></div></section>
      <section className="section section-tint" id="calculator"><div className="container split"><div><div className="eyebrow">Plan with confidence</div><h2 style={{fontSize:36,lineHeight:1.1,color:'var(--ink)',margin:'0 0 18px'}}>Know your numbers before you apply.</h2><p>Explore an estimate for your Development Loan. Adjust the amount and term to find a repayment that feels right for you.</p><ul style={{padding:0,listStyle:'none',lineHeight:2.4,fontSize:14}}><li><CheckCircle2 size={17} color="var(--primary)"/> No API calls. Your estimate stays in your browser.</li><li><CheckCircle2 size={17} color="var(--primary)"/> Transparent reducing-balance estimate.</li><li><CheckCircle2 size={17} color="var(--primary)"/> Apply when you’re ready.</li></ul><a className="button button-dark" href="/apply/loan">Apply for this loan <ArrowRight size={15}/></a></div><div className="calculator"><h3><Calculator size={21} color="var(--primary}"/> Loan calculator</h3><div className="range-row"><div className="range-label"><span>Loan amount</span><strong>{money(amount)}</strong></div><input type="range" min="50000" max="1500000" step="10000" value={amount} onChange={e=>setAmount(+e.target.value)}/></div><div className="range-row"><div className="range-label"><span>Loan term</span><strong>{term} months</strong></div><input type="range" min="6" max="60" step="6" value={term} onChange={e=>setTerm(+e.target.value)}/></div><div className="outputs"><div className="output">Monthly repayment<strong>{money(monthly)}</strong></div><div className="output">Total interest<strong>{money(monthly*term-amount)}</strong></div><div className="output">Total repayable<strong>{money(monthly*term)}</strong></div></div><a className="button button-primary" style={{width:'100%'}} href="/apply/loan">Start application <ArrowRight size={15}/></a></div></div></section>
      <section className="section" id="invest"><div className="container panel"><div style={{maxWidth:650}}><div className="eyebrow">For Kenyans everywhere</div><h2>Invest in Kenya from anywhere in the world.</h2><p>Diaspora membership gives you a secure, transparent way to save, invest and share in Kenya’s growth—wherever you are.</p><a className="button button-primary" href="/diaspora">Explore diaspora investment <ArrowRight size={15}/></a></div></div></section>
      <section className="quote"><div className="container"><div className="section-head"><div><div className="eyebrow">Our members, in their words</div><h2>Progress is better together.</h2></div></div><div className="quote-grid">{testimonials.map(([name,years,quote])=><div className="quote-card" key={name}><p>{quote}</p><strong>{name}</strong><span>{years} · Kenya</span></div>)}</div></div></section>
    </main>
    <footer className="footer" id="contact"><div className="container footer-grid"><div><a className="logo" href="#home"><span className="crest">E</span><span style={{color:'#fff'}}>Ezra<br/><small>SACCO</small></span></a><p style={{marginTop:20}}>A trusted SACCO for a stronger financial future. Licensed and regulated by SASRA.</p></div><div><h4>Explore</h4><a href="#about">About Ezra</a><a href="#products">Savings & investment</a><a href="#calculator">Loans & calculator</a><a href="/diaspora">Diaspora</a></div><div><h4>Member support</h4><a href="/portal">Member portal</a><a href="/news">News & updates</a><a href="/learn">Financial literacy</a><a href="/legal/privacy-policy">Privacy policy</a></div><div><h4>Talk to us</h4><p>Nairobi, Kenya<br/>Mon–Fri, 8:00am–5:00pm</p><a href="tel:+254112272061">+254 112 272 061</a><a href="mailto:hello@ezrasacco.co.ke">hello@ezrasacco.co.ke</a><a href="https://wa.me/254112272061">WhatsApp an officer</a></div></div><div className="container footer-bottom"><span>© 2026 Ezra SACCO. All rights reserved.</span><span>SASRA License No.  CS/1420 · Member funds insured</span></div></footer>
    <a className="whatsapp" aria-label="Talk to a SACCO officer" href="https://wa.me/254112272061?text=Hello!%20I%20would%20like%20to%20enquire%20about%20joining%20Ezra%20SACCO."><MessageCircle size={24}/></a>
  </>
}
